FROM node:16-alpine

WORKDIR app

# Otimizando a camada de install usando o cache do docker
COPY package*.json .

# Instala as dependências usando cache caso o package.json não tenha sido alterado
RUN npm install --no-package-lock --loglevel error --legacy-peer-deps

COPY . .

EXPOSE 8080

CMD [ "npm", "run",  "start" ]
